[workspace]
resolver = "2"
members = [
    "crates/blob-store",
    "crates/encrypted-storage", 
    "crates/relay-service",
    "crates/wa-bot",
    "crates/whatsmeow",
    "crates/wire-protocol",
]

[workspace.dependencies]
anyhow = "1.0"
tokio = { version = "1.46", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tarpc = { version = "0.36", features = ["serde-transport", "tcp", "serde-transport-json"] }
blake3 = "1.5"
thiserror = "2"
brotli = "8"

[profile.test]
# Optimize test compilation without losing debug info
opt-level = 1
debug = true
debug-assertions = true
overflow-checks = true
incremental = true

[profile.bench]
# Optimize benchmarks
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
codegen-units = 1