[workspace]

resolver = "2"
members = ["crates/*"]
edition = "2024"
rust-version = "1.83.0"

[workspace.dependencies]
tarpc = { version = "0.36.0"}
brotli = { version = "8"}
blake3 = { version = "1.5.1"}
thiserror = { version = "2"}