# Development Docker Compose for Zoe Relay Server
# Provides only Redis for local development - run the relay server with cargo

services:
  redis:
    image: redis:7-alpine
    container_name: zoe-redis-dev
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_dev_data:/data
      - ./.config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50m

  # Optional: Redis management interface for development
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: zoe-redis-commander-dev
    restart: unless-stopped
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - management

volumes:
  # Development Redis data (ephemeral by default)
  redis_dev_data:
    driver: local