[package]
name = "zoe-client"
version = "0.1.0"
edition = "2024"

[dependencies]
# Wire protocol for crypto utilities
zoe-wire-protocol = { path = "../wire-protocol" }

# Async runtime
tokio = { workspace = true, features = ["io-util"] }
tokio-util = { workspace = true, features = ["codec"] }
futures = { workspace = true }
rand = { workspace = true }

# Logging
tracing = "0.1"

# QUIC and TLS support
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring"] }

# Cryptographic dependencies
ed25519-dalek = { version = "2.0", features = ["rand_core"] }

# Additional utilities
hex = "0.4"
async-trait = "0.1"

# Error types for documentation examples
thiserror = { workspace = true }

# RPC and futures for relay service traits
tarpc = { workspace = true }
anyhow = { workspace = true }

[[example]]
name = "echo_message_client"
path = "examples/echo_message_client.rs"

[[example]]
name = "blob_client"
path = "examples/blob_client.rs"


[dev-dependencies]
# Testing framework
tokio-test = "0.4"
tokio = { workspace = true, features = ["test-util", "macros", "rt-multi-thread"] }

clap = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = "0.3"
tempfile = "3.8"