[package]
name = "zoe-client"
version = "0.1.0"
edition = "2024"

[dependencies]
# Wire protocol for crypto utilities
zoe-wire-protocol = { path = "../wire-protocol" }

# Async runtime
tokio = { workspace = true, features = ["io-util"] }
tokio-util = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }

# Logging
tracing = { workspace = true }

# QUIC and TLS support
quinn = { workspace = true }
rustls = { workspace = true }

# Cryptographic dependencies
ed25519-dalek = { workspace = true }

# Additional utilities
hex = { workspace = true }
async-trait = { workspace = true }

# Error types for documentation examples
thiserror = { workspace = true }

# RPC and futures for relay service traits
tarpc = { workspace = true }
anyhow = { workspace = true }

[[example]]
name = "echo_message_client"
path = "examples/echo_message_client.rs"

[[example]]
name = "blob_client"
path = "examples/blob_client.rs"


[dev-dependencies]
# Testing framework
tokio-test = { workspace = true }
tokio = { workspace = true, features = ["test-util", "macros", "rt-multi-thread"] }

clap = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
tempfile = { workspace = true }