[package]
name = "zoe-relay"
version = "0.1.0"
edition = "2024"
description = "Zoe relay server providing QUIC transport with ML-DSA-44-based authentication"
license = "MIT OR Apache-2.0"

[[bin]]
name = "zoe-relay"
path = "src/main.rs"

[dependencies]
zoe-relay-server = { path = "../../crates/relay" }
zoe-app-primitives = { path = "../../crates/app-primitives" }
zoe-wire-protocol = { path = "../../crates/wire-protocol" }

anyhow.workspace = true
clap.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
hex.workspace = true
tokio.workspace = true
rand.workspace = true
rustls.workspace = true
