[package]
name = "zoeyr-wire-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { workspace = true, features = ["serde"] }
ed25519-dalek = { version = "2.0.0", features = ["serde"] }
postcard = "1.1.2"
serde = "1.0.219"
blake3 = { version = "1.5", features = ["serde"] }
tarpc = { workspace = true}
rand = "0.8"
