[package]
name = "zoeyr-wire-protocol"
version = "0.1.0"
edition = "2021"
description = "Zoeyr wire protocol with dynamic authentication, ed25519-derived TLS certificates, and relay service definitions"
license = "MIT OR Apache-2.0"

[dependencies]
# Async runtime
tokio = { workspace = true }

# Serialization
serde = { workspace = true, features = ["derive"] }
postcard = { version = "1.0", features = ["use-std"] }
heapless = "0.7.2"

# Cryptography
ed25519-dalek = { version = "2.0", features = ["rand_core", "serde", "pkcs8"] }
rand = "0.8"

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Hashing
blake3 = { workspace = true, features = ["serde"] }

# QUIC transport
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rcgen = "0.12"

# Networking utilities
socket2 = "0.5"

# Certificate parsing
x509-parser = "0.16"
hex = "0.4"
uuid = { version = "1.0", features = ["v4"] }

# Encoding
base64 = "0.21"

# Logging
tracing = "0.1"

# Async utilities  
async-trait = "0.1"

# RPC and futures for relay service traits
tarpc = { workspace = true }
futures-util = "0.3"

[dev-dependencies]
# Testing framework
tokio-test = "0.4"
test-case = "3.0"
proptest = "1.0"
quickcheck = "1.0"
mockall = "0.12"
tempfile = "3.0"
serial_test = "3.0"

# Assertion utilities
assert_matches = "1.5"
pretty_assertions = "1.4"

# Additional testing utilities
criterion = "0.5"
hex-literal = "0.4"
chrono = { version = "0.4", features = ["serde"] }

[features]
default = []
client = []
server = []
