[package]
name = "zoeyr-relay"
version = "0.1.0"
edition = "2021"
description = "Zoeyr relay server providing QUIC transport with ed25519 authentication"
license = "MIT OR Apache-2.0"

[dependencies]
# Wire protocol for crypto utilities
zoeyr-wire-protocol = { path = "../wire-protocol" }

# Async runtime
tokio = { workspace = true, features = ["io-util"] }

# Error handling
anyhow = { workspace = true }

# Logging
tracing = "0.1"

# QUIC and TLS support
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring"] }

# Cryptographic dependencies
ed25519-dalek = { version = "2.0", features = ["rand_core"] }

# Additional utilities
hex = "0.4"
async-trait = "0.1"

# Error types for documentation examples
thiserror = { workspace = true }

[dev-dependencies]
# Testing framework
tokio-test = "0.4"
tokio = { workspace = true, features = ["test-util", "macros", "rt-multi-thread"] }

# Random number generation for tests
rand = "0.8"

# Additional utilities for testing
futures = "0.3"
tracing-subscriber = "0.3"

# Error types for testing (already in dependencies above)
