[package]
name = "zuppy"
version = "0.1.0"
edition = "2024"

[dependencies]
# GPUI from zed
gpui = "0.2.1"
gpui-component = "0.3.0-preview1"

# ZOE sepcifics
zoe-app-primitives = { path = "../../crates/app-primitives" }
zoe-wire-protocol = { path = "../../crates/wire-protocol" }
zoe-state-machine = { path = "../../crates/state-machine" }
zoe-client = { path = "../../crates/client" }

tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
futures.workspace = true
rust-embed = "8.8.0"
anyhow.workspace = true
gpui-router = "0.2.4"
serde_json.workspace = true
eyeball-im.workspace = true

# smallvec is included here for convenience, it is used by gpui when creating
# components that can have children. uncomment this line or
# use `cargo add smallvec` to add it to your project
#smallvec = "1.13.2"
