[package]
name = "zuppy"
version = "0.1.0"
edition = "2024"

[dependencies]
# GPUI from zed
gpui = "0.2.0"

# ZOE sepcifics
zoe-app-primitives = { path = "../../crates/app-primitives" }
zoe-wire-protocol = { path = "../../crates/wire-protocol" }
zoe-client = { path = "../../crates/client" }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
futures  = { workspace = true }

# smallvec is included here for convenience, it is used by gpui when creating
# components that can have children. uncomment this line or
# use `cargo add smallvec` to add it to your project
#smallvec = "1.13.2"
