# Nextest configuration for the Zoe workspace

[profile.default]
test-threads = 4

[profile.ci]
# Optimized for CI
test-threads = 4

[profile.fast]
# Fast tests with more parallelism
test-threads = 8 
