[package]
name = "zoe-signal-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
presage = { git = "https://github.com/whisperfish/presage" }
presage-store-sled = { git = "https://github.com/whisperfish/presage" }
