[package]
name = "zoe-state-machine"
version = "0.1.0"
edition = "2024"

[dependencies]
zoe-wire-protocol = { path = "../wire-protocol" }
serde = { version = "1.0", features = ["derive"] }
blake3 = "1.5"
ed25519-dalek = "2.1"
postcard = "1.0"
aes-gcm = "0.10"
rand = "0.8"
thiserror = "1.0"

[dev-dependencies]
rand = "0.8"
chrono = "0.4"
